### ISSUE TITLE
Cannot find config

### ISSUE THREAD

**Issue by pathikrit** [edulify/play-hikaricp.edulify.com#25]
I am using Play 2.2.x, Scala 2.10.4 and play-hikaricp 1.0.0 (on 1.0.0 since that is what you I should use with Play 2.2 and I am not in a position to upgrade play now) and I am including config files using `db.foo.hikaricp.file` (my database is not under default but under foo)

When I do `play run`, it works fine. If I do `play start`, I get this stacktrace:

```
Play server process ID is 78193
2014-09-26 14:46:30,869 [main] [info] application - Starting HikariCP connection pool...
2014-09-26 14:46:33,825 [main] [info] application - Loading Hikari configuration from Play configuration.
2014-09-26 14:46:33,846 [main] [info] application - Loading from file configured by db.default.hikaricp.file that is Some(conf/db/merlin/TickerLife/nydev.properties)
2014-09-26 14:46:33,847 [main] [info] application - Loading Hikari configuration from conf/db/merlin/TickerLife/nydev.properties
2014-09-26 14:46:33,878 [main] [info] application - Properties: {dataSource.password=**secret stuff**, dataSource.user=**not putting here****, dataSource.url=jdbc:sqlserver:/localhost:1433, dataSourceClassName=com.microsoft.sqlserver.jdbc.SQLServerDataSource}
2014-09-26 14:46:36,905 [main] [info] application - Loading Hikari configuration from Play configuration.
Oops, cannot start the server.
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:313)
	at scala.None$.get(Option.scala:311)
	at com.edulify.play.hikaricp.HikariCPConfig.mapFromPlayConfiguration(HikariCPConfig.scala:63)
	at com.edulify.play.hikaricp.HikariCPConfig.getHikariConfig(HikariCPConfig.scala:31)
	at com.edulify.play.hikaricp.HirakiCPDBApi$$anonfun$1.apply(HirakiCPDBApi.scala:34)
	at com.edulify.play.hikaricp.HirakiCPDBApi$$anonfun$1.apply(HirakiCPDBApi.scala:32)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.Set$Set3.foreach(Set.scala:115)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
	at scala.collection.SetLike$class.map(SetLike.scala:93)
	at scala.collection.AbstractSet.map(Set.scala:47)
	at com.edulify.play.hikaricp.HirakiCPDBApi.<init>(HirakiCPDBApi.scala:32)
	at com.edulify.play.hikaricp.HikariCPPlugin.hirakiCPDBApi$lzycompute(HikariCPPlugin.scala:31)
	at com.edulify.play.hikaricp.HikariCPPlugin.hirakiCPDBApi(HikariCPPlugin.scala:31)
	at com.edulify.play.hikaricp.HikariCPPlugin.onStart(HikariCPPlugin.scala:37)
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88)
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:88)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:18)
	at play.api.Play$.start(Play.scala:87)
	at play.core.StaticApplication.<init>(ApplicationProvider.scala:52)
	at play.core.server.NettyServer$.createServer(NettyServer.scala:243)
	at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:279)
	at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:274)
	at scala.Option.map(Option.scala:145)
	at play.core.server.NettyServer$.main(NettyServer.scala:274)
	at play.core.server.NettyServer.main(NettyServer.scala)

```

Looks like it is still looking for configs in the .conf files. (To be clear, I have 2 databases under db.foo1 and db.foo2).

**Comment by megazord** [comment]
This is probably fixed at master branch now.
