### ISSUE TITLE
Instructions to use latest hikari plugin with Play 2.2.x

### ISSUE THREAD

**Issue by pathikrit** [edulify/play-hikaricp.edulify.com#27]
In the README it says "Note, it can be made to work with Play 2.2.x of the PlayFramework, but it requires changing the dependencies as the current build relies on the Play 2.3.x plugin."

It is not very clear regarding what to do. Can I use 1.5.0 hikari play plugin with Play 2.2.x? If yes, what dependencies do I need to change and where and how??

When I try to use 1.5.0 with 2.2.x, I get this on `play start`:

```scala
java.lang.NoSuchMethodException: play.core.server.NettyServer.mainDevHttpMode(play.core.SBTLink, play.core.SBTDocHandler, int)
	at java.lang.Class.getMethod(Class.java:1665)
	at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$1.apply(PlayRun.scala:232)
	at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$1.apply(PlayRun.scala:91)
	at scala.Function7$$anonfun$tupled$1.apply(Function7.scala:35)
	at scala.Function7$$anonfun$tupled$1.apply(Function7.scala:34)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
[trace] Stack trace suppressed: run last main/compile:run for the full output.
[error] (main/compile:run) java.lang.NoSuchMethodException: play.core.server.NettyServer.mainDevHttpMode(play.core.SBTLink, play.core.SBTDocHandler, int)
[error] Total time: 14 s, completed Sep 26, 2014 3:18:19 PM
```

**Comment by megazord** [comment]
Guys, I'm closing this issue since I think there is no practical way to support a wide range of play versions.
